services:
  - type: web
    name: opsconnect
    env: static
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: ./out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
